
#ifndef GRAPH_BASED_GENOTYPE_CONSTRAINT_H
#define GRAPH_BASED_GENOTYPE_CONSTRAINT_H

#include "graphBased/nodeConstraint.h"

 namespace GraphBased {


    /**
     * \brief class representating the constraint of a genotype for a representation.
     * 
     * The GenotypeConstraint is generated by a representation class, and used to create or modify a genotype.
     * 
     * The GenotypeConstraint stores multiple NodeConstraint with corresponding ranges.
     * For example, a genotype with 
     *  - nodeConstraints = {constraint0, constraint1},
     *  - ranges = {{1, 5}, {3}},
     * can create individuals with 1 to 5 nodes corresponding to the "constraint0" and 3 nodes corresponding to the "constraint1".
     */
    class GenotypeConstraint {



        protected:

            /// @brief The vector of node constraint.
            std::vector<std::unique_ptr<NodeConstraint>> nodeConstraints;

            /// @brief vector of Node ranges.
            std::vector<std::pair<size_t, size_t>> nodeRanges;
        public:
            /**
             * \brief Default Constructor.
             */
            GenotypeConstraint() {};

            // Disable copying to avoid accidental copies (use references or pointers instead).
            GenotypeConstraint(const GenotypeConstraint&) = delete;
            GenotypeConstraint& operator=(const GenotypeConstraint&) = delete;


            /**
             * \brief Constructor with one constraint and range (for quick construction)
             * 
             * \param[in] nodeConstraint single NodeConstraint to initialize the GenotypeConstraint
             * \param[in] minRange minimum number of nodes in the group.
             * \param[in] maxRange minimum number of nodes in the group.
             */
            GenotypeConstraint(const NodeConstraint& nodeConstraint, size_t minRange, size_t maxRange
            ) : nodeRanges{std::make_pair(minRange, maxRange)} {
                nodeConstraints.push_back(std::move(nodeConstraint.cloneUniquePtr()));
            };

            /**
             * \brief return the number of node constraint.
             */
            size_t size() const;

            /**
             * \brief add a node constraint with its range.
             * 
             * \param[in] nodeConstraint node constraint added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeConstraint(const NodeConstraint& nodeConstraint, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief add a node constraint with its range.
             * 
             * \param[in] nodeConstraint unique_ptr of node constraint added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeConstraint(std::unique_ptr<NodeConstraint> nodeConstraint, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief Return the node constraint at specified index.
             * 
             * \param[in] idx specified index
             */
            const NodeConstraint& getNodeConstraintAt(size_t idx) const;

            /**
             * \brief Return the range at specified index.
             * 
             * \param[in] idx specified index
             */
            const std::pair<size_t, size_t>& getRangeAt(size_t idx) const;

            /**
             * \brief return a copy of the current GenotypeConstraint by dupplicating each NodeConstraint and range
             */
            std::unique_ptr<GenotypeConstraint> cloneUniquePtr() const;
    };
}

#endif // GRAPH_BASED_GENOTYPE_CONSTRAINT_H