
#ifndef GENOTYPE_REQUIREMENTS_H
#define GENOTYPE_REQUIREMENTS_H

#include "node/nodeRequirements.h"

namespace Node {


    /**
     * \brief class representating the requirements of a genotype for a representation.
     * 
     * The GenotypeRequirements is generated by a representation class, and used to create or modify a genotype.
     * 
     * The GenotypeRequirements stores multiple NodeRequirements with corresponding ranges.
     * For example, a genotype with 
     *  - nodeRequirements = {requirements0, requirements1},
     *  - ranges = {{1, 5}, {3}},
     * can create individuals with 1 to 5 nodes corresponding to the "requirements0" and 3 nodes corresponding to the "requirements1".
     */
    class GenotypeRequirements {

        protected:
            /// @brief The vector of node requirements.
            std::vector<NodeRequirements> nodeRequirements;

            /// @brief vector of Node ranges.
            std::vector<std::pair<size_t, size_t>> nodeRanges;

        
        public:

            /**
             * \brief Default Constructor.
             */
            GenotypeRequirements() {};


            /**
             * \brief Constructor with requirements and ranges
             * 
             * \param[in] nodeRequirements single NodeRequirements to initialize the GenotypeRequirements
             * \param[in] nodeRange single range.
             */
            GenotypeRequirements(const NodeRequirements& nodeRequirements, const std::pair<size_t, size_t>& nodeRange
            ) : nodeRequirements{nodeRequirements}, nodeRanges{nodeRange} {};

            /**
             * \brief Constructor with requirements and ranges
             * 
             * \param[in] nodeRequirements vector of NodeRequirements to initialize the GenotypeRequirements
             * \param[in] nodeRanges vector of ranges.
             */
            GenotypeRequirements(
                const std::vector<NodeRequirements>& nodeRequirements,
                const std::vector<std::pair<size_t, size_t>>& nodeRanges
            ) : nodeRequirements{nodeRequirements}, nodeRanges{nodeRanges} {
                if(nodeRequirements.size() != nodeRanges.size()){
                    throw std::runtime_error("GenotypeRequirements:Constructor: size of requirements and ranges mismatch.");
                }
            };

            /**
             * \brief return the number of node requirements.
             */
            size_t size() const;

            /**
             * \brief add a node requirements with its range.
             * 
             * \param[in] nodeRequirements node requirements added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeRequirements(const NodeRequirements& nodeRequirements, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief Return the node requirements at specified index.
             * 
             * \param[in] idx specified index
             */
            const NodeRequirements& getNodeRequirementsAt(size_t idx) const;

            /**
             * \brief Return the range at specified index.
             * 
             * \param[in] idx specified index
             */
            const std::pair<size_t, size_t>& getRangeAt(size_t idx) const;
            
            /**
             * \brief Return the vector of node requirements.
             */
            const std::vector<NodeRequirements>& getNodeRequirements() const;

            /**
             * \brief Return the vector of ranges.
             */
            const std::vector<std::pair<size_t, size_t>>& getRanges() const;
    };
}

#endif // GENOTYPE_REQUIREMENTS_H