
#ifndef GENOTYPE_GENERATOR_H
#define GENOTYPE_GENERATOR_H

#include "node/nodeGenerator.h"

namespace Node {


    /**
     * \brief class representating the generator of a genotype for a representation.
     * 
     * The GenotypeGenerator is generated by a representation class, and used to create or modify a genotype.
     * 
     * The GenotypeGenerator stores multiple NodeGenerator with corresponding ranges.
     * For example, a genotype with 
     *  - nodeGenerators = {generator0, generator1},
     *  - ranges = {{1, 5}, {3}},
     * can create individuals with 1 to 5 nodes corresponding to the "generator0" and 3 nodes corresponding to the "generator1".
     */
    class GenotypeGenerator {



        protected:

            /// @brief The vector of node generator.
            std::vector<std::unique_ptr<NodeGenerator>> nodeGenerators;

            /// @brief vector of Node ranges.
            std::vector<std::pair<size_t, size_t>> nodeRanges;
        public:
            /**
             * \brief Default Constructor.
             */
            GenotypeGenerator() {};

            // Disable copying to avoid accidental copies (use references or pointers instead).
            GenotypeGenerator(const GenotypeGenerator&) = delete;
            GenotypeGenerator& operator=(const GenotypeGenerator&) = delete;


            /**
             * \brief Constructor with one generator and range (for quick construction)
             * 
             * \param[in] nodeGenerator single NodeGenerator to initialize the GenotypeGenerator
             * \param[in] minRange minimum number of nodes in the group.
             * \param[in] maxRange minimum number of nodes in the group.
             */
            GenotypeGenerator(const NodeGenerator& nodeGenerator, size_t minRange, size_t maxRange
            ) : nodeRanges{std::make_pair(minRange, maxRange)} {
                nodeGenerators.push_back(std::move(nodeGenerator.cloneUniquePtr()));
            };

            /**
             * \brief return the number of node generator.
             */
            size_t size() const;

            /**
             * \brief add a node generator with its range.
             * 
             * \param[in] nodeGenerator node generator added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeGenerator(const NodeGenerator& nodeGenerator, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief add a node generator with its range.
             * 
             * \param[in] nodeGenerator unique_ptr of node generator added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeGenerator(std::unique_ptr<NodeGenerator> nodeGenerator, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief Return the node generator at specified index.
             * 
             * \param[in] idx specified index
             */
            NodeGenerator& getNodeGeneratorAt(size_t idx);

            /**
             * \brief Return the range at specified index.
             * 
             * \param[in] idx specified index
             */
            const std::pair<size_t, size_t>& getRangeAt(size_t idx) const;

            /**
             * \brief return a copy of the current GenotypeGenerator by dupplicating each NodeGenerator and range
             */
            std::unique_ptr<GenotypeGenerator> cloneUniquePtr() const;
    };
}

#endif // GENOTYPE_GENERATOR_H