
#ifndef GENOTYPE_TEMPLATE_H
#define GENOTYPE_TEMPLATE_H

#include "node/nodeTemplate.h"

namespace Node {


    /**
     * \brief class representating the template of a genotype for a representation.
     * 
     * The GenotypeTemplate is generated by a representation class, and used to create or modify a genotype.
     * 
     * The GenotypeTemplate stores multiple NodeTemplate with corresponding ranges.
     * For example, a genotype with 
     *  - nodeTemplates = {template0, template1},
     *  - ranges = {{1, 5}, {3}},
     * can create individuals with 1 to 5 nodes corresponding to the "template0" and 3 nodes corresponding to the "template1".
     */
    class GenotypeTemplate {

        protected:
            /// @brief The vector of node template.
            std::vector<NodeTemplate> nodeTemplates;

            /// @brief vector of Node ranges.
            std::vector<std::pair<size_t, size_t>> nodeRanges;

        
        public:

            /**
             * \brief Default Constructor.
             */
            GenotypeTemplate() {};

            /**
             * \brief Constructor with templates and ranges
             */
            GenotypeTemplate(
                const std::vector<NodeTemplate>& nodeTemplates,
                const std::vector<std::pair<size_t, size_t>>& nodeRanges
            ) : nodeTemplates{nodeTemplates}, nodeRanges{nodeRanges} {
                if(nodeTemplates.size() != nodeRanges.size()){
                    throw std::runtime_error("GenotypeTemplate:Constructor: size of template and ranges mismatch.");
                }
            };

            /**
             * \brief return the number of node templates.
             */
            size_t size() const;

            /**
             * \brief add a node template with its range.
             * 
             * \param[in] nodeTemplate node template added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeTemplate(const NodeTemplate& nodeTemplate, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief Return the node template at specified index.
             * 
             * \param[in] idx specified index
             */
            const NodeTemplate& getNodeTemplateAt(size_t idx) const;

            /**
             * \brief Return the range at specified index.
             * 
             * \param[in] idx specified index
             */
            const std::pair<size_t, size_t>& getRangeAt(size_t idx) const;
            
            /**
             * \brief Return the vector of node templates.
             */
            const std::vector<NodeTemplate>& getNodeTemplates() const;

            /**
             * \brief Return the vector of ranges.
             */
            const std::vector<std::pair<size_t, size_t>>& getRanges() const;
    };
}

#endif // GENOTYPE_TEMPLATE_H