
#ifndef GENOTYPE_TEMPLATE_H
#define GENOTYPE_TEMPLATE_H

#include "node/nodeTemplate.h"

namespace Node {


    /**
     * \brief class representating the template of a genotype for a representation.
     * 
     * The GenotypeTemplate is generated by a representation class, and used to create or modify a genotype.
     * 
     * The GenotypeTemplate stores multiple NodeTemplate with corresponding ranges.
     * For example, a genotype with 
     *  - nodeTemplates = {template0, template1},
     *  - ranges = {{1, 5}, {3}},
     * can create individuals with 1 to 5 nodes corresponding to the "template0" and 3 nodes corresponding to the "template1".
     */
    class GenotypeTemplate {



        protected:

            /// @brief The vector of node template.
            std::vector<std::unique_ptr<NodeTemplate>> nodeTemplates;

            /// @brief vector of Node ranges.
            std::vector<std::pair<size_t, size_t>> nodeRanges;
        public:
            /**
             * \brief Default Constructor.
             */
            GenotypeTemplate() {};

            // Disable copying to avoid accidental copies (use references or pointers instead).
            GenotypeTemplate(const GenotypeTemplate&) = delete;
            GenotypeTemplate& operator=(const GenotypeTemplate&) = delete;


            /**
             * \brief Constructor with one template and range (for quick construction)
             * 
             * \param[in] nodeTemplate single NodeTemplate to initialize the GenotypeTemplate
             * \param[in] nodeRange single range.
             */
            GenotypeTemplate(const NodeTemplate& nodeTemplate, const std::pair<size_t, size_t>& nodeRange
            ) : nodeRanges{nodeRange} {
                nodeTemplates.push_back(std::move(nodeTemplate.cloneUniquePtr()));
            };

            /**
             * \brief return the number of node template.
             */
            size_t size() const;

            /**
             * \brief add a node template with its range.
             * 
             * \param[in] nodeTemplates node template added
             * \param[in] minRange minimal range, default to 1.
             * \param[in] maxRange maximal range, default to 0. If value is 0, it is set to minRange.
             */
            void addNodeTemplate(const NodeTemplate& nodeTemplates, size_t minRange = 1, size_t maxRange = 0);

            /**
             * \brief Return the node template at specified index.
             * 
             * \param[in] idx specified index
             */
            NodeTemplate& getNodeTemplateAt(size_t idx);

            /**
             * \brief Return the range at specified index.
             * 
             * \param[in] idx specified index
             */
            const std::pair<size_t, size_t>& getRangeAt(size_t idx) const;

            /**
             * \brief return a copy of the current GenotypeTemplate by dupplicating each NodeTemplate and range
             */
            std::unique_ptr<GenotypeTemplate> cloneUniquePtr() const;
    };
}

#endif // GENOTYPE_TEMPLATE_H